sudo: required

services:
  - docker

script:
  - docker-compose build
  - docker-compose run ubuntu 'echo hello'
  - docker-compose run centos 'echo goodbye'

notifications:
  email:
    - collins.christopher@gmail.com
