language: generic

sudo: required

env:
  - BUILD=ubuntu
  - BUILD=centos

services:
  - docker

script:
  - "docker-compose build $BUILD"
  - "docker-compose run $BUILD 'echo hello'"

notifications:
  email:
    - collins.christopher@gmail.com
