version: '2'
services:
  cowrie:
    build:
      context: .
    volumes:
      - /srv/cowrie:/etc/cowrie
    ports:
      - "2222:2222"
    environment:
      DEBUG: "true"
      AUTHBIND_ENABLED: ""
      IP_ADDRESS: 10.0.0.1
      CHN_SERVER: "http://chnserver"
      FEEDS_SERVER: "localhost"
      DEPLOY_KEY: "FOO"
      COWRIE_JSON: "/etc/cowrie/cowrie.json"
      TAGS: ""
