---
  pkgs:
    - git
    - jq
    - python-virtualenv

  cowrie_pip_pkgs:
    - bcrypt

  cowrie_repo: http://github.com/cowrie/cowrie

  cowrie_version: v2.0.1

  cowrie_dir: /opt/cowrie
  cowrie_user: cowrie

  runit_service_dir: /etc/service/cowrie
