---
  pkgs:
    - git
    - jq
    - python-virtualenv

  cowrie_repo: http://github.com/cowrie/cowrie

  cowrie_version: 1.5.2

  cowrie_dir: /opt/cowrie
  cowrie_user: cowrie

  runit_service_dir: /etc/service/cowrie
